version: "3"
services:
  samba:
    build: . 
    container_name: trabalho_samba
    tty: true
    environment:
      - TZ=GMT
    ports:
      - 139:139
      - 445:445
    
    command: 
      -u "admin;admin"
      -u "user1;xpto"
      -u "user2;xpto"
      -p

    volumes: 
      - ./private:/private:z
      - ./public:/public:z
      - ./usr1:/usr1:z
      - ./usr2:/usr2:z
      - ./cfg/samba/smb.conf:/etc/samba/smb.conf:ro 
